name: Test

on:
  workflow_dispatch:

jobs:
  upload:
    name: Upload file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git pull
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            android-app/build.gradle.kts

  download:
    name: download file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git pull
      - uses: actions/download-artifact@v4
        with:
          path: release_bin
